server:
  port: 8887

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



github.client.id: 29a2d1ad14bb78c67520
github.client.secret: 9b89536447767d5e1062d4ce96a85a0aa85b89a5
github.redirect.uri: http://localhost:8887/callback
